server:
  port: ${SERVER_PORT}

spring:
  application:
    name: neffi-laft

  datasource:
    url: jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}

app:
  neffi-trust-url: ${APP_NEFFI_TRUST_URL}
  bypass-auth: ${AUTH_BYPASS}
  cors:
    allowed-origins:
      - "http://localhost:5000"
      - "http://localhost:5010"
      - "http://localhost:5173"
      - "https://*.replit.dev"
      - "https://*.replit.app"
  restrictiveList:
    validationProcessName: VALIDACION_CLIENTE
    validationEventDescription: Validación de cliente contra listas restrictivas
    returnsLinf: SI
    maxBulkRecords: 20

logging:
  level:
    com.neffi: DEBUG
    org.springframework.security: INFO
